services:
  tladmin:
    build: .
    container_name: tladmin
    restart: always
    env_file:
      - .env.production
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - tladmin-network

networks:
  tladmin-network:
    driver: bridge
